### 1. Array Creation and Basic Operations


1. **Create a 1D array of the first 10 positive integers.**
   - Print the array.
   - Find the sum of all elements in the array.
   - Calculate the mean of the elements.

In [3]:
import numpy as np

# Create a 1D array of the first 10 positive integers
arr = np.arange(1, 11)

# Print the array
print("1D array:\n", arr)

# Find the sum of all elements in the array
sum_of_elements = np.sum(arr)
print("\nSum of elements:", sum_of_elements)

# Calculate the mean of the elements
mean_of_elements = np.mean(arr)
print("Mean of elements:", mean_of_elements)

1D array:
 [ 1  2  3  4  5  6  7  8  9 10]

Sum of elements: 55
Mean of elements: 5.5




2. **Create a 2D array of shape (3, 4) with random integers between 1 and 10.**
   - Print the array.
   - Find the maximum and minimum values in the array.
   - Calculate the sum of each row and each column

In [1]:
import numpy as np

# Create a 2D array of shape (3, 4) with random integers between 1 and 10
arr_2d = np.random.randint(1, 11, size=(3, 4))

# Print the array
print("2D array:\n", arr_2d)

# Find the maximum and minimum values in the array
max_value = np.max(arr_2d)
min_value = np.min(arr_2d)
print("\nMaximum value:", max_value)
print("Minimum value:", min_value)

# Calculate the sum of each row
row_sums = np.sum(arr_2d, axis=1)
print("\nSum of each row:", row_sums)

# Calculate the sum of each column
col_sums = np.sum(arr_2d, axis=0)
print("Sum of each column:", col_sums)

2D array:
 [[7 1 5 4]
 [6 8 3 9]
 [9 6 3 2]]

Maximum value: 9
Minimum value: 1

Sum of each row: [17 26 20]
Sum of each column: [22 15 11 15]


### 2. Array Indexing and Slicing

3. **Create a 1D array of 20 random integers between 1 and 100.**
   - Print the array.
   - Print the elements from index 5 to 15.
   - Print every second element of the array.

In [4]:
import numpy as np

# Create a 1D array of 20 random integers between 1 and 100
arr_1d = np.random.randint(1, 101, size=20)

# Print the array
print("1D array:\n", arr_1d)

# Print the elements from index 5 to 15
print("\nElements from index 5 to 15:\n", arr_1d[5:16])

# Print every second element of the array
print("\nEvery second element:\n", arr_1d[::2])

1D array:
 [24 70 89 43 13 87 96 42 45 73 74 10  8 87 57 87  9 80 11 46]

Elements from index 5 to 15:
 [87 96 42 45 73 74 10  8 87 57 87]

Every second element:
 [24 89 13 96 45 74  8 57  9 11]


4. **Create a 2D array of shape (5, 5) with random integers between 1 and 50.**
   - Print the array.
   - Extract and print the second row.
   - Extract and print the third column.
   - Extract and print a 3x3 subarray from the original array

In [5]:
import numpy as np

# Create a 2D array of shape (5, 5) with random integers between 1 and 50
arr_2d = np.random.randint(1, 51, size=(5, 5))

# Print the array
print("2D array:\n", arr_2d)

# Extract and print the second row
second_row = arr_2d[1, :]
print("\nSecond row:\n", second_row)

# Extract and print the third column
third_column = arr_2d[:, 2]
print("\nThird column:\n", third_column)

# Extract and print a 3x3 subarray from the original array
subarray = arr_2d[1:4, 1:4]
print("\n3x3 subarray:\n", subarray)

2D array:
 [[28 42  1 13 47]
 [ 4 46 12 11 17]
 [39 39 34 15 26]
 [50 20 32 42 10]
 [17 29 34  3 43]]

Second row:
 [ 4 46 12 11 17]

Third column:
 [ 1 12 34 32 34]

3x3 subarray:
 [[46 12 11]
 [39 34 15]
 [20 32 42]]


### 3. Array Manipulation

5. **Create two 1D arrays of 10 random integers each.**
   - Concatenate the two arrays.
   - Sort the concatenated array.
   - Find the unique elements in the concatenated array

In [6]:
import numpy as np

# Create two 1D arrays of 10 random integers each
arr1 = np.random.randint(1, 51, size=10)
arr2 = np.random.randint(1, 51, size=10)

# Concatenate the two arrays
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated array:\n", concatenated_arr)

# Sort the concatenated array
sorted_arr = np.sort(concatenated_arr)
print("\nSorted array:\n", sorted_arr)

# Find the unique elements in the concatenated array
unique_elements = np.unique(concatenated_arr)
print("\nUnique elements:\n", unique_elements)

Concatenated array:
 [ 8 22 25 37  3 35 35 35  6 11  1 25 18 47 21 26  7 48 49  3]

Sorted array:
 [ 1  3  3  6  7  8 11 18 21 22 25 25 26 35 35 35 37 47 48 49]

Unique elements:
 [ 1  3  6  7  8 11 18 21 22 25 26 35 37 47 48 49]


6. **Create a 2D array of shape (4, 4) with random integers between 1 and 20.**
   - Print the array.
   - Flatten the array into a 1D array.
   - Reshape the flattened array back into a 2D array of shape (2, 8)

In [7]:
import numpy as np

# Create a 2D array of shape (4, 4) with random integers between 1 and 20
arr_2d = np.random.randint(1, 21, size=(4, 4))

# Print the array
print("2D array:\n", arr_2d)

# Flatten the array into a 1D array
flattened_arr = arr_2d.flatten()
print("\nFlattened array:\n", flattened_arr)

# Reshape the flattened array back into a 2D array of shape (2, 8)
reshaped_arr = flattened_arr.reshape(2, 8)
print("\nReshaped array:\n", reshaped_arr)

2D array:
 [[ 2 19  2  5]
 [ 5 18  7 10]
 [20 17 13  6]
 [15  7 15  5]]

Flattened array:
 [ 2 19  2  5  5 18  7 10 20 17 13  6 15  7 15  5]

Reshaped array:
 [[ 2 19  2  5  5 18  7 10]
 [20 17 13  6 15  7 15  5]]


### 4. Mathematical and Statistical Operations

7. **Create a 1D array of 15 random integers between 1 and 50.**
   - Print the array.
   - Calculate and print the standard deviation of the array.
   - Find and print the index of the maximum value in the array.
   - Normalize the array (scale the values to a range between 0 and 1).


In [8]:
import numpy as np

# Create a 1D array of 15 random integers between 1 and 50
arr_1d = np.random.randint(1, 51, size=15)

# Print the array
print("1D array:\n", arr_1d)

# Calculate and print the standard deviation of the array
std_dev = np.std(arr_1d)
print("\nStandard deviation:", std_dev)

# Find and print the index of the maximum value in the array
max_index = np.argmax(arr_1d)
print("Index of maximum value:", max_index)

# Normalize the array (scale the values to a range between 0 and 1)
normalized_arr = (arr_1d - np.min(arr_1d)) / (np.max(arr_1d) - np.min(arr_1d))
print("\nNormalized array:\n", normalized_arr)

1D array:
 [49 47 27 16 15 46 15 39  7 50 42 29 48 44 24]

Standard deviation: 14.418506626323452
Index of maximum value: 9

Normalized array:
 [0.97674419 0.93023256 0.46511628 0.20930233 0.18604651 0.90697674
 0.18604651 0.74418605 0.         1.         0.81395349 0.51162791
 0.95348837 0.86046512 0.39534884]


8. **Create two 2D arrays of shape (3, 3) with random integers between 1 and 10.**
   - Print both arrays.
   - Perform element-wise addition, subtraction, and multiplication of the arrays.
   - Calculate the dot product of the arrays

In [9]:
import numpy as np

# Create two 2D arrays of shape (3, 3) with random integers between 1 and 10
arr1 = np.random.randint(1, 11, size=(3, 3))
arr2 = np.random.randint(1, 11, size=(3, 3))

# Print both arrays
print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

# Perform element-wise addition, subtraction, and multiplication of the arrays
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2

print("\nElement-wise addition:\n", addition)
print("\nElement-wise subtraction:\n", subtraction)
print("\nElement-wise multiplication:\n", multiplication)

# Calculate the dot product of the arrays
dot_product = np.dot(arr1, arr2)
print("\nDot product:\n", dot_product)

Array 1:
 [[ 1  7  5]
 [ 1 10  6]
 [ 1  1  4]]

Array 2:
 [[3 2 7]
 [5 9 3]
 [3 6 8]]

Element-wise addition:
 [[ 4  9 12]
 [ 6 19  9]
 [ 4  7 12]]

Element-wise subtraction:
 [[-2  5 -2]
 [-4  1  3]
 [-2 -5 -4]]

Element-wise multiplication:
 [[ 3 14 35]
 [ 5 90 18]
 [ 3  6 32]]

Dot product:
 [[ 53  95  68]
 [ 71 128  85]
 [ 20  35  42]]
