#NumPy
NumPy (Numerical Python) is an open source Python library that aids in mathematical, scientific, engineering, and data science programming.
ցան
NumPy is the fundamental package for scientific computing with Python. It contains:
* a powerful N-dimensional array object
* extension package to Python for multi-dimensional arrays
* designed for scientific computation dom number capabilities
——
linear algebra, Fourier transform, and ran
* NumPy can also be used as an efficient multi-dimensional container of generic dat
a.
* This allows NumPy to seamlessly and speedily integrate with a wide variety of dat
abases.
* NumPy is an incredible library to perform mathematical and statistical operations because it is fast and memory
efficient.closer to hardware (efficiency)


In [10]:
# Load in NumPy (Import NumPy Package)
import numpy as np



# ndarray object
ndarray_object = np.array([1, 2, 3, 4, 5])

# The most important object defined in NumPy is an N-dimensional array type called ndarray.
# It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.
# Each element in ndarray is an object of data-type object (called dtype).
import numpy as np
x = np.array(object, dtype=None)

In [11]:
 a=[1,2,3,4,5]

In [14]:
print(type(a))
# <class 'list'>

<class 'list'>


In [15]:
np_a = np.array(a)

In [17]:
np_a = np.array([1, 2, 3, 4, 5])
print(np_a)

[1 2 3 4 5]


In [19]:
print(type(np_a))
# <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


Why it is useful: Memory-efficient container that provides fast numerical operations.

In [20]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

296 µs ± 4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
a= np.arange(1000)
%timeit a**2

1.56 µs ± 277 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
# 1-D
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [24]:
#print dimensions
a.ndim

1

In [25]:
 #shape
a.shape

(4,)

In [26]:
# 2-D
np.array([[0, 1, 2], [3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
# 2-D
b = np.array([[0, 1, 2], [3, 4, 5]])  # Assign the array to the variable 'b'
b.ndim  # Now you can access its attributes

2

In [29]:
b.shape

(2, 3)

In [33]:
# 3D
C = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

In [35]:
# 3D
C = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

# Access the 'ndim' attribute of the array 'C' (using the correct capitalization)
C.ndim

3

In [37]:
# 3D
C = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

# Access the shape attribute of the array 'C' (using the correct capitalization)
C.shape

(2, 2, 2)

#Creating NumPy Arrays From a List

In [39]:
# We know how to create a list, right [1,2,3]
my_list = [1,2,3]

In [40]:
 np.array(my_list)


array([1, 2, 3])

In [41]:
# We can convert a matrix which is also a list to array
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [42]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.array(my_matrix).shape

(3, 3)

#Functions for creating arrays
A new ndarray object can be created by any of the following array creation routines:
•
list_nparray = np.array(python_list,dtype)
arange_array = np.arange(start,end,step,dtype)
⚫ zero_array = np.zeros(shape,dtype)
⚫ ones_array = np.ones(shape,dtype)
·
#linspace_array = np.linspace(start_element, end_element, num_of_elements)
• empty_array = np.empty(shape, dtype)
random_array = np.random.randint(start,end,num_elements))
⚫ which will Return evenly spaced values within a given interval.


In [46]:
#using arrange function -->arange is an array-valued version of the built-in Python range function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b = np.arange(1, 10, 2) #start, end (exclusive), step
b


array([1, 3, 5, 7, 9])

#Linspace
• Return evenly spaced numbers over a specified interval.

In [48]:
#using Linspace
a = np.linspace(0, 5, 6) #start, end, number of points
a

array([0., 1., 2., 3., 4., 5.])

In [49]:
# I want to get 3 evenly spaced points between 0 to 10
np.linspace(0,10, 7)
1.66666667, 3.33333333, 5.

(1.66666667, 3.33333333, 5.0)

#zeros and ones
• Generate arrays of zeros or ones

In [50]:
np.zeros(3)

array([0., 0., 0.])

In [51]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [52]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

eye --> Creates an identity matrix
• An indentity matrix if you are not familier is used
in linear algebra problems and is a two dimentioanl squared
matrix means number of rows are same as columns with diagonals of ones and everything is zero

In [57]:
import re  # Import the 're' module for regular expression operations

c = re.compile  # Example usage of 're' to compile a regular expression
np.eye(3)
#Return a 2-D array with ones on the diagonal and zeros elsewhe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
import numpy as np

d = np.eye(3, 2)  # 3 is number of rows, 2 is number of columns, index of diagonal starts with 0
print(d)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [63]:
# Create array using diag function
a = np.diag([7, 9, 3, 4])
a = a
print(a)

[[7 0 0 0]
 [0 9 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#Extract diagonal

In [64]:
np.diag(a)

array([7, 9, 3, 4])

Random --> Numpy also has lots of ways to create random number arrays:
Return random integers from start (inclusive) to end (exclusive). random_array = np.random.randint(1,121,5)


In [66]:
random_array = [62, 26, 22, 105, 113]
print(random_array)

[62, 26, 22, 105, 113]


In [69]:
# Create an array of the given shape and populate it with random samples
# from a uniform distribution over [0, 1).
a = np.random.rand(4)
a

array([0.93352034, 0.19361781, 0.71594347, 0.70207692])

In [71]:
# Return a sample (or samples) from the "standard normal" distribution. ***Gaussian***
a = np.random.randn(100)
a

array([ 2.07077894, -0.12110033,  0.75797975,  0.94349024, -0.0979785 ,
       -1.45658656,  2.72905918,  0.39076335, -0.43682354, -0.68319872,
       -0.8380675 , -2.0063227 , -0.66565392,  0.25457799,  2.7627163 ,
        0.63813966, -0.39576451, -0.36964579,  0.80032321, -0.06744289,
       -0.72550569,  0.73897708,  1.29371803, -0.49548407,  0.59387235,
       -0.38763382,  0.72889094, -0.00551959,  0.5416614 , -1.67774673,
       -0.99373661, -0.8073229 , -0.72892226,  0.32131025, -1.53962335,
        0.33532827, -0.81694696, -0.37998195, -0.94085568,  0.74210608,
       -0.78018674,  0.79950065,  0.82593905,  0.52559191,  0.03837968,
       -0.14328095,  0.70251207,  1.31314768, -3.36651961,  0.79446347,
        1.3474122 ,  0.06479482,  0.27749568, -1.74696121,  2.19973672,
       -1.2586869 ,  1.39585065,  0.22253404,  0.47249408,  0.86965469,
       -0.39934021, -0.74047301, -0.56244289, -0.0560294 , -0.34112251,
       -0.34232741, -1.26149392, -0.12209515, -0.32755425,  0.45

#Copy Array

In [74]:
import numpy as np

a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)
22
2

[100   2   3]
[100   2   3]


2

#Reshape Array

In [76]:
arr = np.arange(25)
print(arr)
print(arr.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [77]:
# Notice the two sets of brackets
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print("Shape of a: {}".format(a.shape))


[[1 2 3]
 [4 5 6]]
Shape of a: (2, 3)


#Reshaping

In [80]:
b = a.reshape(3,2)
print(b)
print("Shape of b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
Shape of b: (3, 2)


#Transpose Array

In [82]:
a = np.array([[1,2,3], [4,5,6]])
print("Shape: {}".format(a.shape))
print(a)

Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [86]:
c = a.T
print(c)
#Flattening Da[25]
#[36]


[[1 4]
 [2 5]
 [3 6]]


In [87]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the el ements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [88]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [91]:
#Sorting along an axis:
# axis=1 --> row and axis=0 -->column
a = np.array([[3, 1, 2], [0, 0, 4]])
b = np.sort(a, axis=1)
print(b)
np.array([[5, 4, 6], [2, 8, 2]])
np.sort(a, axis=1)

[[1 2 3]
 [0 0 4]]


array([[1, 2, 3],
       [0, 0, 4]])

#Add/Remove operations on a numpy array

In [94]:
import numpy as np

a = np.array([4,7,8])
a = np.append(a, [2,4,5])
print('Numpy array after addition: ',a)

Numpy array after addition:  [4 7 8 2 4 5]


In [95]:
a = np.delete(a,2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 7 2 4 5]


#Indexing
The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):


In [97]:
a = np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [99]:
# For multidimensional arrays, indexes are tuples of integers:
a = np.diag([1, 2, 3])
print(a)
print(a[2, 1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [101]:
a[2, 1] = 5  # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [102]:
a = np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [104]:
import numpy as np # import the numpy library and give it an alias 'np'

np.array([ 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]) # create the numpy array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [105]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([ 5,  7,  9, 11])

In [108]:
#we can also combine assignment and slicing:
a = np.arange(10)
a = a[5:]
a

array([5, 6, 7, 8, 9])

In [114]:
a[5:]
a = a
a

array([0, 1, 2, 3, 4])

In [117]:
b = np.arange(5)
Laran = b
b


array([0, 1, 2, 3, 4])

In [119]:
a = np.arange(10) # Recreate 'a' with 10 elements
b = np.arange(5)
a[5:] = b[::-1]  # Now 'a' has enough space
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [120]:
 a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

#Fancy Indexing
NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views.

In [123]:
a = np.random.randint(0, 20, 5)
a

array([ 7,  3,  4,  5, 12])

In [124]:
 a[a % 2 == 0]

array([ 4, 12])

In [133]:
a = [2, 19, 4]
even_numbers = [num for num in a if num % 2 == 0]  # Find even numbers in the list
if even_numbers:  # Check if there are any even numbers
    print(even_numbers[0])  # Print the first even number
else:
    print("No even numbers found in the list.")
print(-1)


2
-1


In [136]:
np.arange(0, 101, 10)
a

[2, 19, 4]

In [144]:
a[[2, 0, 2, 1, 2]]  # Use valid indices

array([ 4,  2,  4, 19,  4])

In [ ]:
# New values can be assigned
a[[9, 7]] = -200

#ad Operations
1. Basic Operations
with scalars
In [67] a = np.array([1, 2, 3, 4]) #create an array
print(a) print(a+1)

In [146]:
a = np.array([1, 2, 3, 4]) #create an array
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [147]:
a ** 2

array([ 1,  4,  9, 16])

All arithmetic operates elementwise

In [148]:
b = np.ones (4) + 1
b

array([2., 2., 2., 2.])

In [149]:
a - b

array([-1.,  0.,  1.,  2.])

In [150]:
a * b

array([2., 4., 6., 8.])

In [159]:
 a
np.array([[1, 2], [3, 4], [5, 6]]) - np.array([[4, 4], [4, 4], [4, 4]])

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

# adding a and b

In [170]:
print('Sum of a and b :\n', a+b)
print('Sum of a and b')
print([[5, 6],
       [7, 8]])
print([9, 10])

Sum of a and b :
 [[ 5  6  2]
 [ 7  8  5]
 [ 9 10  8]]
Sum of a and b
[[5, 6], [7, 8]]
[9, 10]


In [173]:
# multiply a and b - elementwise multiplication
print('Product of a and b :\n', np.multiply(a, b))

# print the output on a new line
print()

Product of a and b :
 [[ 4  8  1]
 [12 16  6]
 [20 24 15]]



In [166]:
# array multiplication
C = np.diag([1, 2, 3, 4])
print(C @ C)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [167]:
 # matrix multiplication
a =np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[4,4,1], [4,4,2], [4,4,3]])
print('Matrix multiplication: \n', np.matmul(a,b))

Matrix multiplication: 
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [174]:
a = np.array([1, 2, 3, 4])
b=np.array([5, 2, 2, 4])
b

array([5, 2, 2, 4])

In [176]:
import numpy as np  # Import the NumPy library and give it an alias 'np'

array = np.array([False, True, False, True])  # Now you can use np.array()
print(array)

[False  True False  True]


In [180]:
a > b

array([False, False,  True, False])

In [179]:
a = b = []
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = a + b
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [181]:
np.array_equal(a, b)

False

In [182]:
np.array_equal(a, c)

False

In [183]:
#Logical Operations
In [81]: a = np.array([1, 1, 0, 0], dtype=bool)
b=np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [185]:
np.logical_and(a, b)


array([ True, False, False, False])

In [186]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [187]:
np.log(a)

<ipython-input-187-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [189]:
a = np.arange(4)
b = np.array([1, 2, 3, 4]) #Modified to have the same shape as a
a + b

array([1, 3, 5, 7])

#Shape Mismatch

In [193]:
import numpy as np # Import the numpy module

# Clear the overwritten variable
del array

# Now you can use the array function from numpy
np.array([
    -np.inf,
    0.
])

array([-inf,   0.])

#evaluates e^x for each element in a given input
20.08553692, 54.59815003])
Basic Reductions
Bata
computing sums
ValueError
Traceback (most recent call last)
<ipython-input-86-7ded08b2ed74> in <module>
1 a = np.arange(4)
----> 2a + np.array([1, 2])
ValueError: operands could not be broadcast together with shapes (4,) (2,)

In [194]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [197]:
#sum by rows and by columns
x = np.array([[1, 1], [2, 2]])
print(x)


[[1 1]
 [2 2]]


In [198]:
x.sum(axis=0)
#columns first dimension

array([3, 3])

In [199]:
x.sum(axis=1) #rows (second dimension)

array([2, 4])

In [200]:
#Other reductions
In [91]: x = np.array([1, 3, 2])
x.min()

1

In [201]:
x.max()

3

In [202]:
 x.argmin() # index of minimum element

0

In [203]:
x.argmax() # index of maximum element

1

In [204]:
#Statistics Data s
normal_array = np.arange(0,10,1)
print('Array is ', format (normal_array))

Array is  [0 1 2 3 4 5 6 7 8 9]


In [207]:
### Min
print('min element is ', np.min(normal_array))
# Μαχ  <-- This line contained a typo and was not a valid comment
print('max element is ',np.max(normal_array))
### Sum
print('Sum of elements in array is ', np. sum(normal_array))
### Mean
print('mean of elements in array is ', np.mean (normal_array))
### Median
print('median of elements in array is ', np.median (normal_array))
# Sd <-- This is not a valid Python command and should likely be a comment
print('standard deviation of elements in array is ', np.std (normal_array))

min element is  0
max element is  9
Sum of elements in array is  45
mean of elements in array is  4.5
median of elements in array is  4.5
standard deviation of elements in array is  2.8722813232690143
